# Generated by Django 3.2.3 on 2021-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
