# Generated by Django 3.2.3 on 2021-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattemptstatus',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
