# Generated by Django 3.2.3 on 2021-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_answerstatus_correctness'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.IntegerField(default=50),
        ),
    ]
